name: Github-Docker Hub MLOps pipeline - KB

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}


on:
  push:
    branches:
    - main


jobs:

  ci_pipeline:
       runs-on: ubuntu-latest

       steps:
        - uses: actions/checkout@v1
          with:
            fetch-depth: 0

        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip --user
            pip install flake8
            pip install mccabe
            pip install -r requirements.txt

        - name: Run flake8 with mccabe - PEP8 analyzer and code complexity analyzer
          run: flake8 --max-line-length 120 --max-complexity 10 --statistics src app.py


  cd_pipeline:
       runs-on: ubuntu-latest
       needs: [ci_pipeline]

       steps:
        - uses: actions/checkout@v2
        - name: docker login
          run: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        - name: Get current date # get the date of the build
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
        - name: Build the Docker image # push The image to the docker hub
          run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
        - name: Docker Push
          run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}